person:
  name: 张三${random.uuid}
  age: ${random.int}
  boss: false
  birthday: 2020/06/15
  map: {k1: v1, k2: v2}
  objectList:
    - ${person.hello:李四}
    - 王五
    - 赵六
  dog:
    name: ${person.name}的狗
    age: 2

server:
  port: 8080
spring:
  profiles:
    active: dev
---
server:
  port: 8085
spring:
  profiles: dev
---
server:
  port: 8083
spring:
  profiles: prod